# Generated by Django 4.1.7 on 2023-02-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("position", models.CharField(max_length=200)),
                ("date_of_birth", models.CharField(max_length=20)),
                ("nationality", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="competition",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitions",
                to="api.area",
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("tla", models.CharField(max_length=20)),
                ("short_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=250)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="api.area",
                    ),
                ),
                (
                    "squad",
                    models.ManyToManyField(related_name="teams", to="api.player"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="competition",
            name="teams",
            field=models.ManyToManyField(
                related_name="running_competitions", to="api.team"
            ),
        ),
    ]
