# Generated by Django 4.1.7 on 2023-02-20 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_coach"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="competition",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="area",
            name="code",
            field=models.CharField(default="AA", max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competition",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competition",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="coach",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="tla",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
