# Generated by Django 4.1.7 on 2023-02-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_area_options_alter_competition_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="date_of_birth",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="coach",
            name="nationality",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="player",
            name="date_of_birth",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="player",
            name="nationality",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="team",
            name="address",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="team",
            name="short_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
