# Generated by Django 4.1.7 on 2023-02-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_team_squad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
