# Generated by Django 4.1.7 on 2023-02-20 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_player_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="area",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitions",
                to="api.area",
            ),
        ),
    ]
