# Generated by Django 4.1.7 on 2023-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_competition_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="running_competitions", to="api.team"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="squad",
            field=models.ManyToManyField(
                blank=True, related_name="current_teams", to="api.player"
            ),
        ),
    ]
