# Generated by Django 4.1.7 on 2023-02-22 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_coach_date_of_birth_alter_coach_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coach",
            options={
                "ordering": ("name",),
                "verbose_name": "Coach",
                "verbose_name_plural": "Coaches",
            },
        ),
    ]
