# Generated by Django 4.1.7 on 2023-02-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_coach_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="tla",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
