### Browsable API
GET http://localhost:8000/api/v1/ HTTP/1.1


### Import League
POST http://localhost:8000/api/v1/import-league/AU/ HTTP/1.1


### Players filtered by league
GET http://localhost:8000/api/v1/players/PL/ HTTP/1.1

### Players filtered by league
GET http://localhost:8000/api/v1/players/BSA/ HTTP/1.1


### Players filtered by league case insensitive
GET http://localhost:8000/api/v1/players/pl/ HTTP/1.1


### Players filtered by INVALID league
GET http://localhost:8000/api/v1/players/PLA/ HTTP/1.1



### Players filtered by league and team
GET http://localhost:8000/api/v1/players/PL/ARS/ HTTP/1.1


### Teams Detail view
GET http://localhost:8000/api/v1/teams/ARS/ HTTP/1.1


### Teams Detail view
GET http://localhost:8000/api/v1/teams/BOT/ HTTP/1.1


### Teams Detail view is case insensitive
GET http://localhost:8000/api/v1/teams/ars/ HTTP/1.1



### Teams Detail view show players as well
GET http://localhost:8000/api/v1/teams/ARS/?players=true HTTP/1.1

### Teams Detail view show players as well
GET http://localhost:8000/api/v1/teams/BOT/?players=true HTTP/1.1

### Teams Detail view show players as well alternative endpoint
GET http://localhost:8000/api/v1/teams/ARS/players/ HTTP/1.1